### ISSUE TITLE
Screen doesn't scale at all

### ISSUE THREAD

**Issue by smeth194243** [Locke087/EmpData#1]
Program is first run

log in

click submit

As you can see the page extends beyond the viewport, so you have to maximize the window to see any of the buttons

There used to be a bug where once you maximize it you cant partially minimize it, but it looks like you fixed that

**Comment by kodecreer** [comment]
This isn’t a bug. It’s a featur

**Comment by smeth194243** [comment]
I don't agree, but you can save it for last so that you get to other ones first.
